In [1]:
import numpy as np

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x + delta_x) - f(x - delta_x)) / (2 * delta_x)

In [3]:
def my_func1(x):
    return x**2  # x^2

In [4]:
result = numerical_derivative(my_func1, 3)
result

6.000000000012662

In [5]:
def my_func2(x):
    return 3*x*(np.exp(x))  # 3xe^x

In [6]:
result = numerical_derivative(my_func2, 2)
result

66.50150507518049

In [7]:
def numerical_derivative(f, x):
    delta_x = 1e-4  # 10^-4
    grad = np.zeros_like(x)
    print("initial x =", x)
    print("initial grad =", grad)
    print("="*50)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        print("idx =", idx, ", x[idx] =", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        print("grad[idx] =", grad[idx])
        print("grad =", grad)
        print("="*50)
        
        x[idx] = tmp_val
        it.iternext()

    return grad

In [8]:
def my_func3(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return (2*x + 3*x*y + np.power(y, 3))  # 2x + 3xy + y^3

In [9]:
numerical_derivative(my_func3, np.array([3.0, 2.0]))

initial x = [3. 2.]
initial grad = [0. 0.]
idx = (0,) , x[idx] = 3.0
grad[idx] = 7.999999999999119
grad = [8. 0.]
idx = (1,) , x[idx] = 2.0
grad[idx] = 21.000000010040765
grad = [ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [10]:
def my_func4(input_obj):
    w = input_obj[0]
    x = input_obj[1]
    y = input_obj[2]
    z = input_obj[3]
    return (w*x + x*y*z + 3*w + z*np.power(y, 2))  # wx + xyz + 3w + zy^2

In [11]:
numerical_derivative(my_func4, np.array([3.0, 2.0, 3.0, 4.0]))

initial x = [3. 2. 3. 4.]
initial grad = [0. 0. 0. 0.]
idx = (0,) , x[idx] = 3.0
grad[idx] = 5.000000000023874
grad = [5. 0. 0. 0.]
idx = (1,) , x[idx] = 2.0
grad[idx] = 15.000000000000568
grad = [ 5. 15.  0.  0.]
idx = (2,) , x[idx] = 3.0
grad[idx] = 31.999999999996476
grad = [ 5. 15. 32.  0.]
idx = (3,) , x[idx] = 4.0
grad[idx] = 15.000000000000568
grad = [ 5. 15. 32. 15.]


array([ 5., 15., 32., 15.])

In [12]:
numerical_derivative(my_func1, np.array([3.0]))

initial x = [3.]
initial grad = [0.]
idx = (0,) , x[idx] = 3.0
grad[idx] = 6.000000000012662
grad = [6.]


array([6.])