In [2]:
import numpy as np

In [3]:
load_data = np.loadtxt("data/data-01-test-score.csv",
                       delimiter=",", dtype=np.float32)
load_data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [4]:
x_data = load_data[:, :-1]
t_data = load_data[:, [-1]]
print("x_data =", x_data)
print("t_data =", t_data)

x_data = [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
t_data = [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [5]:
W = np.random.rand(3, 1)
b = np.random.rand(1)
print("W =", W, ", b =", b)

W = [[0.64074068]
 [0.20409949]
 [0.2620139 ]] , b = [0.03662858]


In [6]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t - y)**2))/len(x)

In [7]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        
        x[idx] = tmp_val
        it.iternext()

    return grad

In [8]:
def predict(x):
    y = np.dot(x, W) + b
    return y

In [9]:
learning_rate = 1e-6  # 발산 정도에 따라 3~6 사이 적절하게 조절
def f(x): return loss_func(x_data, t_data)


print("initial error value =", loss_func(x_data, t_data),
      ", initial W =", W, ", initial b =", b)

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)

    if step % 4000 == 0:  # 4000번마다 출력
        print("step =", step, ", error value =", loss_func(x_data, t_data),
              ", W =", W, ", b =", b)

initial error value = 5572.137671194481 , initial W = [[0.64074068]
 [0.20409949]
 [0.2620139 ]] , initial b = [0.03662858]
step = 0 , error value = 5145.11960759582 , W = [[0.65263686]
 [0.21607127]
 [0.27428949]] , b = [0.03677038]
step = 4000 , error value = 13.658135227680761 , W = [[0.88749011]
 [0.49247387]
 [0.64705863]] , b = [0.04019603]
step = 8000 , error value = 11.985520545707965 , W = [[0.83597709]
 [0.48003665]
 [0.7092774 ]] , b = [0.04006507]
step = 12000 , error value = 10.70707558035983 , W = [[0.7895202 ]
 [0.47139365]
 [0.76287539]] , b = [0.03986457]
step = 16000 , error value = 9.72410683305132 , W = [[0.74761302]
 [0.46575867]
 [0.80911299]] , b = [0.03960405]
step = 20000 , error value = 8.963965566744903 , W = [[0.70980144]
 [0.46248954]
 [0.84905892]] , b = [0.03929167]
step = 24000 , error value = 8.37288594670042 , W = [[0.67567803]
 [0.46106319]
 [0.88362023]] , b = [0.0389344]
step = 28000 , error value = 7.9108518959036624 , W = [[0.64487703]
 [0.4610548