In [1]:
import numpy as np

In [2]:
load_data = np.loadtxt("data/data-01-test-score.csv", delimiter=",", dtype=np.float32)
load_data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [3]:
x_data = load_data[:,:-1]
t_data = load_data[:,[-1]]
print("x_data =", x_data)
print("t_data =", t_data)

x_data = [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
t_data = [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [4]:
W = np.random.rand(3, 1)
b = np.random.rand(1)
print("W =", W, ", b =", b)

W = [[0.35645103]
 [0.26787726]
 [0.71504071]] , b = [0.66414776]


In [5]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    return (np.sum((t - y)**2))/len(x)

In [6]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
#     print("initial x =", x)
#     print("initial grad =", grad)
#     print("="*50)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
#         print("idx =", idx, ", x[idx] =", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
#         print("grad[idx] =", grad[idx])
#         print("grad =", grad)
#         print("="*50)
        
        x[idx] = tmp_val
        it.iternext()

    return grad

In [7]:
def predict(x):
    y = np.dot(x, W) + b
    return y

In [8]:
learning_rate = 1e-6  # 3~6 사이 적절하게 조절
f = lambda x: loss_func(x_data, t_data)
print("initial error value =", loss_func(x_data, t_data), ", initial W =", W, ", initial b =", b)

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if step % 4000 == 0:  # 4000번마다 출력
        print("step =", step, ", error value =", loss_func(x_data, t_data), ", W =", W, ", b =", b)

initial error value = 2952.140507404876 , initial W = [[0.35645103]
 [0.26787726]
 [0.71504071]] , initial b = [0.66414776]
step = 0 , error value = 2725.825474567978 , W = [[0.36511682]
 [0.27659585]
 [0.72396921]] , b = [0.66425085]
step = 4000 , error value = 7.128631143699383 , W = [[0.556287  ]
 [0.48874849]
 [0.96504406]] , b = [0.66621318]
step = 8000 , error value = 6.941388828508172 , W = [[0.53697519]
 [0.48816366]
 [0.98439109]] , b = [0.66561998]
step = 12000 , error value = 6.794803001336895 , W = [[0.51954279]
 [0.48834574]
 [1.00116241]] , b = [0.66500505]
step = 16000 , error value = 6.67948468307106 , W = [[0.50380409]
 [0.48910597]
 [1.01572294]] , b = [0.66437126]
step = 20000 , error value = 6.588351383502654 , W = [[0.4895922 ]
 [0.49029239]
 [1.02838336]] , b = [0.66372109]
step = 24000 , error value = 6.516028033917445 , W = [[0.47675702]
 [0.49178329]
 [1.03940843]] , b = [0.66305665]
step = 28000 , error value = 6.45841067962987 , W = [[0.46516353]
 [0.49348177